[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "docs.pisz.pl"
authors = [{name = "Krzysiek Wierzbicki", email = "krzysiekwie@gmail.com"}]
dynamic = ["version", "description"]
